### ISSUE TITLE
Update dates in Readme examples for hacktober

### ISSUE THREAD

**Issue by s-nirali** [itaysk/hacktober-script#1]
For being considered for raising a PR during hacktoberfest, the examples in the README here, https://github.com/itaysk/hacktober-script/blame/master/Readme.md#L18-L22, need to be updated for the `--before` flag with the date `"2019-10-31T23:59:59Z"`. Otherwise, PRs raised on October 31st do not get counted.

**Comment by itaysk** [comment]
Thanks, I'll fix that
